# Generated by Django 3.0.11 on 2021-01-21 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='Insira o enunciado que deve ser exibido ', max_length=1000, verbose_name='Questão')),
                ('explanation', models.TextField(blank=True, help_text='Explicação que deve ser exibida após a questão ser respondida', max_length=2000, verbose_name='Explicação')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Category', verbose_name='Categoria')),
                ('quiz', models.ManyToManyField(blank=True, to='quiz.Quiz', verbose_name='Quiz')),
            ],
        ),
    ]
