# Generated by Django 3.0.11 on 2021-01-21 05:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiChoiceQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.Question')),
            ],
            bases=('quiz.question',),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answers_at_end',
            field=models.BooleanField(default=False, help_text='Correct answer is NOT shown after question. Answers displayed at the end.', verbose_name='Answers at end'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Category', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, help_text='A descrição do quiz', verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='max_questions',
            field=models.PositiveIntegerField(blank=True, help_text='Number of questions to be answered on each attempt.', null=True, verbose_name='Max Questions'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='pass_mark',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Percentage required to pass exam.', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Pass Mark'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='hey', max_length=60, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='url',
            field=models.SlugField(default='hey', help_text='a user friendly url', max_length=60, verbose_name='user friendly url'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='Insira o texto da alternativa que será exibido.', max_length=1000, verbose_name='Alnternativa')),
                ('is_correct', models.BooleanField(default=False, help_text='Esta é a resposta correta?', verbose_name='Correta')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.MultiChoiceQuestion', verbose_name='Questão')),
            ],
        ),
    ]
