# Generated by Django 3.1.8 on 2021-05-21 00:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0002_auto_20210520_1403"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="progress",
            options={
                "verbose_name": "Progresso do Usuário",
                "verbose_name_plural": "Progressos dos Usuários",
            },
        ),
        migrations.AddField(
            model_name="quiz",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Data de Criação",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="progress",
            name="correct_answer",
            field=models.CharField(max_length=10, verbose_name="Respostas Corretas"),
        ),
        migrations.AlterField(
            model_name="progress",
            name="quiz",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.quiz",
                verbose_name="Questionário",
            ),
        ),
        migrations.AlterField(
            model_name="progress",
            name="score",
            field=models.CharField(
                max_length=1024,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^\\d+(?:,\\d+)*\\Z"),
                        code="invalid",
                        message="Enter only digits separated by commas.",
                    )
                ],
                verbose_name="Pontuação",
            ),
        ),
        migrations.AlterField(
            model_name="progress",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AlterField(
            model_name="progress",
            name="wrong_answer",
            field=models.CharField(max_length=10, verbose_name="Respostas Incorretas"),
        ),
    ]
